# Generated by Django 4.0.1 on 2022-01-30 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_comment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
